const fs = require('fs');
fs.mkdirSync('src/app/api/courses', { recursive: true });
const content = [
  "import { NextRequest, NextResponse } from 'next/server'",
  "import { prisma } from '@/lib/prisma'",
  "import { cacheGet, cacheSet } from '@/lib/redis'",
  "import { getSession } from '@/lib/auth'",
  "",
  "const CACHE_TTL = 120",
  "",
  "export async function GET(req: NextRequest) {",
  "  try {",
  "    const { searchParams } = new URL(req.url)",
  "    const subject = searchParams.get('subject') || undefined",
  "    const grade = searchParams.get('grade') ? Number(searchParams.get('grade')) : undefined",
  "    const cacheKey = `courses:${subject ?? 'all'}:${grade ?? 'all'}`",
  "    const cached = await cacheGet(cacheKey)",
  "    if (cached) return NextResponse.json(cached, { headers: { 'X-Cache': 'HIT' } })",
  "    const courses = await prisma.course.findMany({",
  "      where: {",
  "        ...(subject ? { subject } : {}),",
  "        ...(grade ? { grade } : {}),",
  "      },",
  "      include: {",
  "        _count: { select: { lessons: true } },",
  "        lessons: { orderBy: { order: 'asc' } },",
  "      },",
  "      orderBy: { createdAt: 'desc' },",
  "    })",
  "    await cacheSet(cacheKey, courses, CACHE_TTL)",
  "    return NextResponse.json(courses, { headers: { 'X-Cache': 'MISS' } })",
  "  } catch (e) {",
  "    console.error('[GET /api/courses]', e)",
  "    return NextResponse.json({ error: 'Server error' }, { status: 500 })",
  "  }",
  "}",
  "",
  "export async function POST(req: NextRequest) {",
  "  try {",
  "    const session = await getSession()",
  "    if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })",
  "    if (session.role !== 'teacher') return NextResponse.json({ error: 'Forbidden' }, { status: 403 })",
  "    const body = await req.json()",
  "    const { title, description, subject, grade, difficulty, xpReward } = body",
  "    if (!title || !subject) return NextResponse.json({ error: 'title and subject required' }, { status: 400 })",
  "    const course = await prisma.course.create({",
  "      data: {",
  "        title, description: description || '', subject,",
  "        grade: grade != null ? Number(grade) : 1,",
  "        difficulty: difficulty || 'easy', xpReward: xpReward ?? 50,",
  "      },",
  "    })",
  "    return NextResponse.json(course, { status: 201 })",
  "  } catch (e) {",
  "    console.error('[POST /api/courses]', e)",
  "    return NextResponse.json({ error: 'Server error' }, { status: 500 })",
  "  }",
  "}"
].join('\n');

fs.writeFileSync('src/app/api/courses/route.ts', content, 'utf8');
console.log('OK — файл записан');